bosses:
  frostwarden:
    name: "&bFrost Warden"
    health: 500.0
    damage: 10.0
  titanbehemoth:
    name: "&8Titan Behemoth"
    health: 1000.0
    damage: 15.0

arenas:
  arena1:
    world: "world"
    x: 100.5
    y: 65.0
    z: -200.5
    
